FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
COPY ./config/html/index.html ./public/

RUN npm run build
RUN npm install -g serve

CMD ["npm", "run", "start"]
EXPOSE 8000
